"""changes

Revision ID: 4775f7b90d9a
Revises: 2ad27326dc78
Create Date: 2025-08-21 17:16:00.834630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4775f7b90d9a'
down_revision: Union[str, Sequence[str], None] = '2ad27326dc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('student_admission_no_key'), 'student', type_='unique')
    op.drop_column('student', 'admission_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('admission_no', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('student_admission_no_key'), 'student', ['admission_no'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
